Fixes bug with associating user with idea
jmichaelbrown8/elevator-pitch pull request #74
Opened 2022-03-11 07:12 UTC by jmichaelbrown8

#73 

This fixes the bug where an idea doesn't save the user's id and the idea.handlebars always displaying the logged in user (rather than the idea creator).

2022-03-11 18:05 UTC, kimberlym4488 approved these changes

2022-03-11 20:00 UTC, ac524 approved these changes
Looks good to me :)

2022-03-11 20:04 UTC, ac524 requested changes

2022-03-11 20:04 UTC, ac524 commented on models/index.js
> +});
Hey @jmichaelbrown8, in merging changes from the idea upvote branch, we now have an alias conflict over "upvoter", We'll need a new alias name for this.

2022-03-11 20:12 UTC, ac524 commented on models/index.js
> +});
Or maybe I did the merge wrong and the hasMany isn't needed? Not sure in this case without looking through uses more.

2022-03-12 23:48 UTC, ac524 approved these changes
Fixed alias issue, so this is good to go.

2022-03-12 23:48 UTC, merged